import { Server, ExecHistoryEntry, SshKeyMeta } from './api';

export const MOCK_SERVERS: Server[] = [
  {
    id: 'srv-001',
    name: 'prod-api',
    host: '10.0.1.10',
    port: 22,
    user: 'deploy',
    status: 'up',
    latency_ms: 12,
    commands: [
      { id: 'cmd-001', server_id: 'srv-001', label: 'Restart API', command: 'systemctl restart tap-api', confirm: true, timeout_sec: 30, sort_order: 0, pinned: true },
      { id: 'cmd-002', server_id: 'srv-001', label: 'View Logs', command: 'journalctl -u tap-api --no-pager -n 50', confirm: false, timeout_sec: 10, sort_order: 1, pinned: false },
      { id: 'cmd-003', server_id: 'srv-001', label: 'Health Check', command: 'curl -s localhost:8080/health', confirm: false, timeout_sec: 5, sort_order: 2, pinned: true },
    ],
    suites: [
      { id: 'suite-001', server_id: 'srv-001', label: 'Deploy Pipeline' },
    ],
  },
  {
    id: 'srv-002',
    name: 'prod-db',
    host: '10.0.1.20',
    port: 22,
    user: 'postgres',
    status: 'up',
    latency_ms: 8,
    commands: [
      { id: 'cmd-004', server_id: 'srv-002', label: 'DB Status', command: 'pg_isready', confirm: false, timeout_sec: 5, sort_order: 0, pinned: true },
      { id: 'cmd-005', server_id: 'srv-002', label: 'Vacuum Analyze', command: 'vacuumdb --analyze --all', confirm: true, timeout_sec: 120, sort_order: 1, pinned: false },
    ],
    suites: [],
  },
  {
    id: 'srv-003',
    name: 'staging',
    host: '10.0.2.10',
    port: 22,
    user: 'deploy',
    status: 'up',
    latency_ms: 24,
    commands: [
      { id: 'cmd-006', server_id: 'srv-003', label: 'Deploy Branch', command: './deploy.sh --branch main', confirm: true, timeout_sec: 60, sort_order: 0, pinned: true },
      { id: 'cmd-007', server_id: 'srv-003', label: 'Run Tests', command: 'npm test -- --ci', confirm: false, timeout_sec: 90, sort_order: 1, pinned: false },
    ],
    suites: [
      { id: 'suite-002', server_id: 'srv-003', label: 'Smoke Tests' },
      { id: 'suite-003', server_id: 'srv-003', label: 'Integration Tests' },
    ],
  },
  {
    id: 'srv-004',
    name: 'nginx-lb',
    host: '10.0.1.1',
    port: 22,
    user: 'root',
    status: 'down',
    latency_ms: null,
    commands: [
      { id: 'cmd-008', server_id: 'srv-004', label: 'Reload Nginx', command: 'nginx -s reload', confirm: true, timeout_sec: 10, sort_order: 0, pinned: true },
      { id: 'cmd-009', server_id: 'srv-004', label: 'Test Config', command: 'nginx -t', confirm: false, timeout_sec: 5, sort_order: 1, pinned: false },
    ],
    suites: [],
  },
  {
    id: 'srv-005',
    name: 'monitoring',
    host: '10.0.3.10',
    port: 2222,
    user: 'ops',
    status: 'up',
    latency_ms: 31,
    commands: [
      { id: 'cmd-010', server_id: 'srv-005', label: 'Disk Usage', command: 'df -h', confirm: false, timeout_sec: 5, sort_order: 0, pinned: true },
    ],
    suites: [],
  },
];

export const MOCK_HISTORY: ExecHistoryEntry[] = [
  {
    id: 'hist-001',
    server_id: 'srv-001',
    command_id: 'cmd-003',
    command_text: 'curl -s localhost:8080/health',
    exit_code: 0,
    stdout: '{"status":"ok","uptime":"14d 6h 32m","version":"2.4.1"}',
    stderr: null,
    duration_ms: 42,
    device: 'iPhone',
    created_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
  {
    id: 'hist-002',
    server_id: 'srv-001',
    command_id: 'cmd-001',
    command_text: 'systemctl restart tap-api',
    exit_code: 0,
    stdout: null,
    stderr: null,
    duration_ms: 1840,
    device: 'iPhone',
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: 'hist-003',
    server_id: 'srv-002',
    command_id: 'cmd-004',
    command_text: 'pg_isready',
    exit_code: 0,
    stdout: '/var/run/postgresql:5432 - accepting connections',
    stderr: null,
    duration_ms: 18,
    device: 'Apple Watch',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: 'hist-004',
    server_id: 'srv-004',
    command_id: 'cmd-008',
    command_text: 'nginx -s reload',
    exit_code: 1,
    stdout: null,
    stderr: 'nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)',
    duration_ms: 320,
    device: 'iPhone',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
  {
    id: 'hist-005',
    server_id: 'srv-003',
    command_id: 'cmd-007',
    command_text: 'npm test -- --ci',
    exit_code: 0,
    stdout: 'Test Suites: 24 passed, 24 total\nTests: 187 passed, 187 total\nTime: 12.4s',
    stderr: null,
    duration_ms: 12400,
    device: 'iPhone',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
];

export const MOCK_KEYS: SshKeyMeta[] = [
  {
    id: 'key-001',
    label: 'prod-deploy',
    public_key: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHk2Xq8Rm3tFbYG9v4kN0PzKLmEwGhJ8QxVp7T2nM4Ds tap@relay',
    key_type: 'ed25519',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 90).toISOString(),
  },
  {
    id: 'key-002',
    label: 'staging-key',
    public_key: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJwR5mF8vKNp2L0tY6hXcB9sWqDfGk1nOoP3rU7iZ8Ax tap@relay',
    key_type: 'ed25519',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 45).toISOString(),
  },
  {
    id: 'key-003',
    label: 'monitoring-ro',
    public_key: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOlP4nR7sK2wV8mXyF0gH3jA6tBcDq5eN9iL1uW3xZ0Y tap@relay',
    key_type: 'ed25519',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(),
  },
];
